@server=http://localhost:4004
@username=alice
@password=


### Customers
# @name Customers_GET
GET {{server}}/odata/v4/phase-management/Customers
Authorization: Basic {{username}}:{{password}}


### Customers
# @name Customers_POST
POST {{server}}/odata/v4/phase-management/Customers
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "14424804-5b3f-4e8a-95f4-5aa9a681acb7",
  "name": "name-14424804",
  "accountNumber": "accountNumber-14424804",
  "contracts": [
    {
      "ID": "25808528-ecf5-434c-912e-11c1f945fa4d",
      "description": "description-2580852",
      "startDate": "2013-02-06",
      "endDate": "2019-03-09",
      "currency": "currency-2580852",
      "status": "Active",
      "phases": [
        {
          "ID": "26303161-b01c-4bc4-bb55-741fda82335e",
          "name": "name-26303161",
          "startDate": "2017-02-27",
          "endDate": "2009-02-18",
          "monthlyPrice": 5485810924190.94,
          "description": "description-26303161"
        },
        {
          "ID": "26303162-da4a-44b0-a994-af6a2d5d89ad",
          "name": "name-26303162",
          "startDate": "2018-02-20",
          "endDate": "2020-04-06",
          "monthlyPrice": 2547251706436.14,
          "description": "description-26303162"
        }
      ]
    },
    {
      "ID": "25808530-5efb-4680-a95a-fed7978e885a",
      "description": "description-2580853",
      "startDate": "2005-04-22",
      "endDate": "2015-07-01",
      "currency": "currency-2580853",
      "status": "Inactive",
      "phases": [
        {
          "ID": "26043694-5675-47f5-aa71-e42f1c45591d",
          "name": "name-26043694",
          "startDate": "2018-01-28",
          "endDate": "2004-11-18",
          "monthlyPrice": 9315383213243.28,
          "description": "description-26043694"
        },
        {
          "ID": "26043695-e03c-4e29-bf26-3f25e1a35448",
          "name": "name-26043695",
          "startDate": "2016-03-02",
          "endDate": "2016-08-20",
          "monthlyPrice": 4319125081367.39,
          "description": "description-26043695"
        }
      ]
    }
  ]
}


### Customers
# @name Customers_PATCH
PATCH {{server}}/odata/v4/phase-management/Customers/14424804-5b3f-4e8a-95f4-5aa9a681acb7
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "14424804-5b3f-4e8a-95f4-5aa9a681acb7",
  "name": "name-14424804",
  "accountNumber": "accountNumber-14424804",
  "contracts": [
    {
      "ID": "25808528-ecf5-434c-912e-11c1f945fa4d",
      "description": "description-2580852",
      "startDate": "2013-02-06",
      "endDate": "2019-03-09",
      "currency": "currency-2580852",
      "status": "Active",
      "phases": [
        {
          "ID": "26303161-b01c-4bc4-bb55-741fda82335e",
          "name": "name-26303161",
          "startDate": "2017-02-27",
          "endDate": "2009-02-18",
          "monthlyPrice": 5485810924190.94,
          "description": "description-26303161"
        },
        {
          "ID": "26303162-da4a-44b0-a994-af6a2d5d89ad",
          "name": "name-26303162",
          "startDate": "2018-02-20",
          "endDate": "2020-04-06",
          "monthlyPrice": 2547251706436.14,
          "description": "description-26303162"
        }
      ]
    },
    {
      "ID": "25808530-5efb-4680-a95a-fed7978e885a",
      "description": "description-2580853",
      "startDate": "2005-04-22",
      "endDate": "2015-07-01",
      "currency": "currency-2580853",
      "status": "Inactive",
      "phases": [
        {
          "ID": "26043694-5675-47f5-aa71-e42f1c45591d",
          "name": "name-26043694",
          "startDate": "2018-01-28",
          "endDate": "2004-11-18",
          "monthlyPrice": 9315383213243.28,
          "description": "description-26043694"
        },
        {
          "ID": "26043695-e03c-4e29-bf26-3f25e1a35448",
          "name": "name-26043695",
          "startDate": "2016-03-02",
          "endDate": "2016-08-20",
          "monthlyPrice": 4319125081367.39,
          "description": "description-26043695"
        }
      ]
    }
  ]
}


### Customers
# @name Customers_DELETE
DELETE {{server}}/odata/v4/phase-management/Customers/14424804-5b3f-4e8a-95f4-5aa9a681acb7
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Contracts
# @name Contracts_GET
GET {{server}}/odata/v4/phase-management/Contracts
Authorization: Basic {{username}}:{{password}}


### Contracts
# @name Contracts_POST
POST {{server}}/odata/v4/phase-management/Contracts
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "25808528-ecf5-434c-912e-11c1f945fa4d",
  "description": "description-2580852",
  "startDate": "2013-02-06",
  "endDate": "2019-03-09",
  "currency": "currency-2580852",
  "status": "Active",
  "phases": [
    {
      "ID": "26303161-b01c-4bc4-bb55-741fda82335e",
      "name": "name-26303161",
      "startDate": "2017-02-27",
      "endDate": "2009-02-18",
      "monthlyPrice": 5485810924190.94,
      "description": "description-26303161"
    },
    {
      "ID": "26303162-da4a-44b0-a994-af6a2d5d89ad",
      "name": "name-26303162",
      "startDate": "2018-02-20",
      "endDate": "2020-04-06",
      "monthlyPrice": 2547251706436.14,
      "description": "description-26303162"
    }
  ]
}


### Contracts
# @name Contracts_PATCH
PATCH {{server}}/odata/v4/phase-management/Contracts/25808528-ecf5-434c-912e-11c1f945fa4d
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "25808528-ecf5-434c-912e-11c1f945fa4d",
  "description": "description-2580852",
  "startDate": "2013-02-06",
  "endDate": "2019-03-09",
  "currency": "currency-2580852",
  "status": "Active",
  "phases": [
    {
      "ID": "26303161-b01c-4bc4-bb55-741fda82335e",
      "name": "name-26303161",
      "startDate": "2017-02-27",
      "endDate": "2009-02-18",
      "monthlyPrice": 5485810924190.94,
      "description": "description-26303161"
    },
    {
      "ID": "26303162-da4a-44b0-a994-af6a2d5d89ad",
      "name": "name-26303162",
      "startDate": "2018-02-20",
      "endDate": "2020-04-06",
      "monthlyPrice": 2547251706436.14,
      "description": "description-26303162"
    }
  ]
}


### Contracts
# @name Contracts_DELETE
DELETE {{server}}/odata/v4/phase-management/Contracts/25808528-ecf5-434c-912e-11c1f945fa4d
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Phases
# @name Phases_GET
GET {{server}}/odata/v4/phase-management/Phases
Authorization: Basic {{username}}:{{password}}


### Phases
# @name Phases_POST
POST {{server}}/odata/v4/phase-management/Phases
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "26303161-b01c-4bc4-bb55-741fda82335e",
  "name": "name-26303161",
  "startDate": "2017-02-27",
  "endDate": "2009-02-18",
  "monthlyPrice": 5485810924190.94,
  "description": "description-26303161"
}


### Phases
# @name Phases_PATCH
PATCH {{server}}/odata/v4/phase-management/Phases/26303161-b01c-4bc4-bb55-741fda82335e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "26303161-b01c-4bc4-bb55-741fda82335e",
  "name": "name-26303161",
  "startDate": "2017-02-27",
  "endDate": "2009-02-18",
  "monthlyPrice": 5485810924190.94,
  "description": "description-26303161"
}


### Phases
# @name Phases_DELETE
DELETE {{server}}/odata/v4/phase-management/Phases/26303161-b01c-4bc4-bb55-741fda82335e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
